GET http://localhost:8000/users

###
POST http://localhost:8000/users/login
Content-Type: application/json

 {
   "email": "test@me.com",
    "password": "cat"
 }

###

POST http://localhost:8000/users/login
Content-Type: application/json

 {
   "email": "swilliams@me.com",
    "password": "llama"
 }

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "firstName": "Testerson",
    "lastName": "Megee",
    "email": "test@me.com",
    "username": "testertheman",
    "password": "cat"
}
