GET http://localhost:8000/users/all


###

GET http://localhost:8000/users
Authorization: Bearer 

###

GET http://localhost:8000/users
Authorization: Bearer 
###
POST http://localhost:8000/posts
Authorization: Bearer 
Content-Type: application/json

{
"title": "NEW POST",
"body": "STEVES THE MAN AND POSTED THIS",
"comments": []
}


###
POST http://localhost:8000/users/login
Content-Type: application/json

 {
   "email": "test@me.com",
    "password": "cat"
 }

###

POST http://localhost:8000/users/login
Content-Type: application/json

 {
   "email": "swilliams@me.com",
    "password": "llama"
 }

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "firstName": "Testerson",
    "lastName": "Megee",
    "email": "test@me.com",
    "username": "testertheman",
    "password": "cat"
}

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "firstName": "Steve",
    "lastName": "Williams",
    "email": "swilliams@me.com",
    "username": "steveypeve",
    "password": "llama"
}

###

POST http://localhost:8000/comments/5fb42856645af59d2afaa296
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmI2OTIxNjA5ZjhlMGZjNzU4MWFlMTUiLCJmaXJzdE5hbWUiOiJTdGV2ZSIsImxhc3ROYW1lIjoiV2lsbGlhbXMiLCJlbWFpbCI6InN3aWxsaWFtc0BtZS5jb20iLCJ1c2VybmFtZSI6InN0ZXZleXBldmUiLCJwYXNzd29yZCI6IiQyYiQxMCRqMS9hamR4YzcvNTJDdldlMDU5TUQudXhBOC5zaDlPbHJVUVdEN1N4VGgvVERaUVNsQmVCUyIsImNyZWF0ZWRBdCI6IjIwMjAtMTEtMTlUMTU6NDE6MTAuOTgxWiIsInVwZGF0ZWRBdCI6IjIwMjAtMTEtMTlUMTU6NDE6MTAuOTgxWiIsIl9fdiI6MCwiaWF0IjoxNjA1ODAwNTAzfQ.hh1fXjetITKwNvnJgSOtEVcpJz4hntYpzVeZ9ESVejs

{
  
    "body": "No more comment titles!!!??"
}